modLoader="javafml"
loaderVersion="[4,)"
license="Not specified"

[[mods]]
modId="royalcraft"
version="1.0.0"
displayName="RoyalCraft"
displayURL="https://luderspieler.net"
credits="Created using mod maker luderspieler - https://luderspieler.net/about"
authors="Luderspieler"
description="Clash Royale in minecraft"

# Start of user code block mod configuration
# End of user code block mod configuration


# Start of user code block custom mixins
# End of user code block custom mixins

[[dependencies.royalcraft]]
    modId="neoforge"
    type="required"
    versionRange="[21.8.31,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.royalcraft]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.8]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration